"""empty message

Revision ID: be7ccac4ac06
Revises: 
Create Date: 2025-12-17 11:20:21.618171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7ccac4ac06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hackathon_judges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hackathon_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hackathon_id', 'user_id', name='uq_hackathon_judge')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('hackathon_teams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hackathons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organizer_id', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('mode', sa.Enum('online', 'offline', 'hybrid', name='event_mode'), nullable=False),
    sa.Column('participation_type', sa.Enum('individual', 'team', name='participation_type'), nullable=False),
    sa.Column('min_team_size', sa.Integer(), nullable=True),
    sa.Column('max_team_size', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('entry_fee', sa.Float(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('interested_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('upcoming', 'ongoing', 'completed', name='hackathon_status'), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('prizes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hackathon_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('hackathon_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'hackathon_id', name='uq_user_hackathon')
    )
    op.create_table('hackathon_registrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hackathon_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='registration_status'), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['hackathon_teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hackathon_id', 'team_id', name='uq_hackathon_team_registration'),
    sa.UniqueConstraint('hackathon_id', 'user_id', name='uq_hackathon_user_registration')
    )
    op.create_table('hackathon_team_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hackathon_team_id', sa.String(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'COLEADER', 'MEMBER', name='team_member_role'), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hackathon_team_id'], ['hackathon_teams.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hackathon_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('project_title', sa.String(length=255), nullable=False),
    sa.Column('project_desc', sa.Text(), nullable=False),
    sa.Column('github_url', sa.String(length=500), nullable=False),
    sa.Column('live_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['hackathon_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hackathon_id', 'team_id', name='uq_hackathon_team_submission')
    )
    op.create_table('judge_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('judge_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['project_submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'judge_id', name='uq_submission_judge_score')
    )
    op.create_table('winners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project_submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position', 'project_id', name='uq_position_project'),
    sa.UniqueConstraint('project_id', name='uq_project_winner')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('winners')
    op.drop_table('judge_scores')
    op.drop_table('project_submissions')
    op.drop_table('hackathon_team_members')
    op.drop_table('hackathon_registrations')
    op.drop_table('hackathon_interests')
    op.drop_table('hackathons')
    op.drop_table('hackathon_teams')
    op.drop_table('users')
    op.drop_table('hackathon_judges')
    # ### end Alembic commands ###
